Upgrade docker image
mantidproject/dockerfiles pull request #60
Opened 2022-11-16 11:02 UTC by sf1919

Changes to the docker images as follows
- upgrade to java 11
- remove pre-commit
- Add a label

2022-11-16 15:37 UTC, martyngigg requested changes
This looks good. Just one small request.

2022-11-16 15:37 UTC, martyngigg commented on jenkins-node/mantid-builder/docker-images/CentOS7Slim.Dockerfile
Can we add the appropriate `LABEL` command to this image too?

2022-11-16 16:42 UTC, martyngigg requested changes
I've just come across one more thing that would be good to include now.

Apparently our git version is ancient and breaks newer pre-commit (https://github.com/pre-commit/pre-commit-hooks/issues/718).
Can we install a more up-to-date git?

2022-11-18 09:43 UTC, sf1919 commented
I've updated git, added openssl and redone the labels so they work as intended (see https://github.com/mantidproject/dockerfiles/pkgs/container/jenkins-node-centos7-slim for example).

2022-11-18 16:29 UTC, martyngigg requested changes
It's great we've got this working now.

Just a few minor tweaks.

2022-11-18 16:29 UTC, martyngigg commented on development/docker/CentOS7Slim.Dockerfile
> +LABEL org.opencontainers.image.source https://github.com/mantidproject/dockerfiles
Could we move this nearer the top, just under the FROM, as it's metatdata and it would be good to distinguish it from script-like commands.

2022-11-21 08:05 UTC, sf1919 commented on development/docker/CentOS7Slim.Dockerfile
> +RUN yum install -y \
Unfortunately the script is very sensitive as to where I put the remove git command. If it's not directly after the installation of the `isu-release-el7.rpm` I get an error that it does not recognise the command `git`

2022-11-21 09:43 UTC, martyngigg requested changes

2022-11-21 09:43 UTC, martyngigg commented on development/docker/CentOS7Slim.Dockerfile
>    python36-pip \
Just spotted this one. Can we remove this one? We no longer need any python36 stuff.

2022-11-21 09:43 UTC, martyngigg commented on development/docker/CentOS7Slim.Dockerfile
> +RUN yum install -y \
Do we need to remove `git`? I tried starting a plain `centos:7` container and it says `git` is not installed:
```
$ docker run -it centos:7 git --version
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "git": executable file not found in $PATH: unknown.
```

I had a quick go locally and found that having

```
# Install minimal developer tools
RUN yum install -y \
  https://repo.ius.io/ius-release-el7.rpm  \
  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y \
  ccache \
  curl \
  git236 \
  graphviz \
  libXScrnSaver \
  openssl \
  pciutils-libs \
  perl-Digest-MD5 \
  sudo \
  which \
  xorg-x11-server-Xvfb && \
  # Clean up
  rm -rf /tmp/* /var/tmp/*
```

gave me a container than when I ran:

```sh
$ docker run -it ghcr.io/mantidproject/mantid-development-centos7-slim:latest git --version
+ TARGET_USERNAME=abc
+ for rule in '/etc/entrypoint.d/*.sh'
+ source /etc/entrypoint.d/000_change_user_ids.sh
++ set -x
++ PUID=911
++ PGID=911
++ groupmod --non-unique --gid 911 abc
++ usermod --non-unique --uid 911 abc
usermod: no changes
+ for rule in '/etc/entrypoint.d/*.sh'
+ source /etc/entrypoint.d/010_abc_own_directories.sh
++ set -x
++ chown abc:abc /mantid_src
++ chown abc:abc /mantid_build
++ chown abc:abc /mantid_data
++ chown abc:abc /ccache
+ for rule in '/etc/entrypoint.d/*.sh'
+ source /etc/entrypoint.d/020_locale.sh
++ set -x
++ export LANG=C.UTF-8
++ LANG=C.UTF-8
+ CMD='git --version'
+ runuser -u abc -- git --version
git version 2.36.1
```

2022-11-22 09:53 UTC, sf1919 commented on development/docker/CentOS7Slim.Dockerfile
> +RUN yum install -y \
I agree, it seems we don't need to remove git as it doesn't get auto installed by anything else by accident. I've even moved the install of git236 into the main yum install layer to make it neater.

2022-11-22 13:16 UTC, martyngigg approved these changes
This looks fab now 👍🏻

2022-11-22 13:16 UTC, merged