Enable use of windows cloud Jenkins nodes
mantidproject/dockerfiles pull request #63
Opened 2022-12-23 11:24 UTC by MialLewis

2023-02-14 12:01 UTC, robertapplin requested changes
Nice work here! The installation of the required packages and setting up the Jenkins node went quite smoothly. I am just waiting for the test pipeline to finish running https://builds.mantidproject.org/manage/computer/isiscloudwin3-1/

I had a few suggestions for the instructions below

2023-02-15 13:17 UTC, MialLewis commented on Windows/jenkins-node/readme.md
> +10. Start the new `docker` service using `Start-service docker`
I've tested this and have just removed this - I don't think it will be necessary moving forwards after a presumed update.

2023-02-15 13:18 UTC, MialLewis commented on Windows/jenkins-node/readme.md
> +1. Clone the `mantidproject/dockerfiles` repository.
Doesn't really matter, I've written the documentation to be flexible to this regard.

2023-02-15 13:20 UTC, MialLewis commented on Windows/jenkins-node/readme.md
> +6. In a new tab, navigate to the Jenkins home page, from the pipeline table select `testing-new-windows-builder`. From the menu on the left-hand side of the page, select `Build Now`.
As above, I've changed the pipeline to have a specific test label.

2023-02-15 13:27 UTC, robertapplin requested changes
Looks good, just spotted a few typos

2023-02-15 13:27 UTC, robertapplin commented on Windows/jenkins-node/readme.md
> +1. Run `Install-Module -Name DockerMsftProvider -Repository PSGallery -Force`. This is the provider than will enable access to the docker online package repository.
```suggestion
2. Run `Install-Module -Name DockerMsftProvider -Repository PSGallery -Force`. This is the provider that will enable access to the docker online package repository.
```

2023-02-15 13:27 UTC, robertapplin commented on Windows/jenkins-node/readme.md
> +1. Clone the `mantidproject/dockerfiles` repository.
Linking to this repository would make it more convenient to clone

2023-02-15 13:45 UTC, robertapplin approved these changes
Nice work - thanks for the changes

2023-02-16 16:02 UTC, merged